config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  get 'comments/destroy'
  resources :welcomes
  resources :bulletins do
    resources :comments, :only =>[:create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bulletin.rb
class Bulletin < ApplicationRecord
    has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :bulletin
end

app/models/welcome.rb
class Welcome < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bulletins_controller.rb
class BulletinsController < ApplicationController
  before_action :set_bulletin, only: %i[ show edit update destroy ]

  # GET /bulletins or /bulletins.json
  def index
    @bulletins = Bulletin.all
  end

  # GET /bulletins/1 or /bulletins/1.json
  def show
  end

  # GET /bulletins/new
  def new
    @bulletin = Bulletin.new
  end

  # GET /bulletins/1/edit
  def edit
  end

  # POST /bulletins or /bulletins.json
  def create
    @bulletin = Bulletin.new(bulletin_params)

    respond_to do |format|
      if @bulletin.save
        format.html { redirect_to bulletin_url(@bulletin), notice: "Bulletin was successfully created." }
        format.json { render :show, status: :created, location: @bulletin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bulletin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bulletins/1 or /bulletins/1.json
  def update
    respond_to do |format|
      if @bulletin.update(bulletin_params)
        format.html { redirect_to bulletin_url(@bulletin), notice: "Bulletin was successfully updated." }
        format.json { render :show, status: :ok, location: @bulletin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bulletin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bulletins/1 or /bulletins/1.json
  def destroy
    @bulletin.destroy

    respond_to do |format|
      format.html { redirect_to bulletins_url, notice: "Bulletin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bulletin
      @bulletin = Bulletin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bulletin_params
      params.require(:bulletin).permit(:title, :content)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    Comment.create(bulletin_id: params[:bulletin_id], body: params[:comment][:body])
    redirect_to "/bulletins/#{params[:bulletin_id]}"
  end

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to "/bulletins/#{params[:bulletin_id]}"
    end
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :set_welcome, only: %i[ show edit update destroy ]

  # GET /welcomes or /welcomes.json
  def index
    @welcomes = Welcome.all
  end

  # GET /welcomes/1 or /welcomes/1.json
  def show
  end

  # GET /welcomes/new
  def new
    @welcome = Welcome.new
  end

  # GET /welcomes/1/edit
  def edit
  end

  # POST /welcomes or /welcomes.json
  def create
    @welcome = Welcome.new(welcome_params)

    respond_to do |format|
      if @welcome.save
        format.html { redirect_to welcome_url(@welcome), notice: "Welcome was successfully created." }
        format.json { render :show, status: :created, location: @welcome }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /welcomes/1 or /welcomes/1.json
  def update
    respond_to do |format|
      if @welcome.update(welcome_params)
        format.html { redirect_to welcome_url(@welcome), notice: "Welcome was successfully updated." }
        format.json { render :show, status: :ok, location: @welcome }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /welcomes/1 or /welcomes/1.json
  def destroy
    @welcome.destroy

    respond_to do |format|
      format.html { redirect_to welcomes_url, notice: "Welcome was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_welcome
      @welcome = Welcome.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def welcome_params
      params.fetch(:welcome, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bulletins_helper.rb
module BulletinsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/bulletins/_form.html.erb
<%= form_with(model: bulletin, local: true) do |form| %>
  <% if bulletin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bulletin.errors.count, "error") %> prohibited this bulletin from being saved:</h2>

      <ul>
        <% bulletin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bulletins/edit.html.erb
<h1>Editing Bulletin</h1>

<%= render 'form', bulletin: @bulletin %>

<%= link_to 'Show', @bulletin %> |
<%= link_to 'Back', bulletins_path %>

app/views/bulletins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bulletins</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bulletins.each do |bulletin| %>
      <tr>
        <td><%= bulletin.title %></td>
        <td><%= bulletin.content %></td>
        <td><%= link_to 'Show', bulletin %></td>
        <td><%= link_to 'Edit', edit_bulletin_path(bulletin) %></td>
        <td><%= link_to 'Destroy', bulletin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bulletin', new_bulletin_path %>

app/views/bulletins/new.html.erb
<h1>New Bulletin</h1>

<%= render 'form', bulletin: @bulletin %>

<%= link_to 'Back', bulletins_path %>

app/views/bulletins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bulletin.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @bulletin.content %>
</p>

<%= link_to 'Edit', edit_bulletin_path(@bulletin) %> |
<%= link_to 'Back', bulletins_path %>

<%= form_for bulletin_comments_path(@bulletin.id) do |f| %>
<%= f.text_field :body, placeholder: "Reply Comment" %>
<%= f.submit('Reply', style: 'margin-left: 10px') %>
<% end %>

<div style="margin-top:40px;"></div>
<% Bulletin.find(@bulletin.id).comments.each do |comment| %>
<%= comment.body %><%= link_to "Delete", bulletin_comment_path(@bulletin.id, comment.id), method: :delete, data: { confirm: 'Do you want to delete?'} %><hr/>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bulletins</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcomes/_form.html.erb
<%= form_with(model: welcome, local: true) do |form| %>
  <% if welcome.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(welcome.errors.count, "error") %> prohibited this welcome from being saved:</h2>

      <ul>
        <% welcome.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/welcomes/edit.html.erb
<h1>Editing Welcome</h1>

<%= render 'form', welcome: @welcome %>

<%= link_to 'Show', @welcome %> |
<%= link_to 'Back', welcomes_path %>

app/views/welcomes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Welcomes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @welcomes.each do |welcome| %>
      <tr>
        <td><%= link_to 'Show', welcome %></td>
        <td><%= link_to 'Edit', edit_welcome_path(welcome) %></td>
        <td><%= link_to 'Destroy', welcome, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Welcome', new_welcome_path %>

app/views/welcomes/new.html.erb
<h1>New Welcome</h1>

<%= render 'form', welcome: @welcome %>

<%= link_to 'Back', welcomes_path %>

app/views/welcomes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_welcome_path(@welcome) %> |
<%= link_to 'Back', welcomes_path %>